### PR TITLE
Support emulator-10-x86_64

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Review by aosmond — COMMENTED** [review]
I would use FEATURE_ALLOW_ALWAYS in your case to be consistent with the pref. Otherwise looks good to me!

**Comment by lissyx** [comment]
@seinlin I think we could likely merge that soon as well

**Comment by fabricedesre** [comment]
@lissyx we fixed the Wifi issues and the GfxInfo one in 82dff4274cab5ec55e421b68a7c22af586b57b76 and 78c374d919c141746cd802c925c37a2c0a021076

**Comment by seinlin** [comment]
I will pick these two commits and make a fast forward push to gonk branch. Thanks!

**Comment by fabricedesre** [comment]
Merged in https://github.com/kaiostech/gecko-b2g/commit/02e92deb81c901bcd8921ef3758e3cf55a4f5cb6

**Pull request closed without merging**
