### PR TITLE
Fix #67: Check for 'OPEN' on network security parameter

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Review by fabricedesre — CHANGES_REQUESTED** [review]
I think the linter will complain about comparing indexOf() result to -1 and will ask you to use includes() instead. You can check with `./mach lint b2g/chrome/content/default-apps/settings/js/wifi.js`

**Comment by lissyx** [comment]
> I think the linter will complain about comparing indexOf() result to -1 and will ask you to use includes() instead. You can check with `./mach lint b2g/chrome/content/default-apps/settings/js/wifi.js`

Linter complains even more:
```
$ ./mach lint b2g/chrome/content/default-apps/settings/js/wifi.js
error: problem with lint setup, skipping android-api-lint, android-checkstyle, android-javadoc, android-lint, android-test
/home/alexandre/Documents/codaz/Mozilla/MiscWork/B2G.KaiOS/gecko/b2g/chrome/content/default-apps/settings/js/wifi.js
  85:9  error  Replace `!network.security.trim().toUpperCase().includes('OPEN')` with `⏎······!network.security⏎········.trim()⏎········.toUpperCase()⏎········.includes("OPEN")⏎····`                                                                      prettier/prettier (eslint)
  97:9  error  Replace `!network.ssid.trim().length·||·!network.security.trim().toUpperCase().includes('OPEN')` with `⏎······!network.ssid.trim().length·||⏎······!network.security⏎········.trim()⏎········.toUpperCase()⏎········.includes("OPEN")⏎····`  prettier/prettier (eslint)
```

**Comment by fabricedesre** [comment]
I just run it with the `--fix` option for that kind of issues.

**Comment by lissyx** [comment]
I'm rebuilding to ensure `.includes()` works correctly and I made no mistake, but I've fixed all of the lint nits

**Comment by lissyx** [comment]
@fabricedesre this should both work and make linter happy :)

**Comment by fabricedesre** [comment]
Cherry picked in https://github.com/kaiostech/gecko-b2g/commit/356fb9f4389a006fed452dc809efc9cc5aba641f

**Pull request closed without merging**
